# 01 - Data Cleaning
**Project:** Credit Approval Readiness — predicting credit card approval odds

**Goal of this notebook:** load the raw dataset, understand what we're working with, handle missing values and inconsistent types, and save a clean version to `data/processed/` for EDA and modeling.

Dataset: [Predicting Credit Card Approvals](https://www.kaggle.com/datasets/devzohaib/predicting-credit-card-approvals)

In [59]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

## 1. Load the raw data

In [60]:
# Update this path if yours filename is different once downloaded from Kaggle
df = pd.read_csv('../data/raw/cc_approvals.data', header=None)

print(f"Shape: {df.shape}")
df.head()

Shape: (690, 16)

  0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  00202    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g  00043  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  00280  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  00100    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  00120    0  +

## 2. First look at the data

Before touching anything, understand what you actually have:
- How many rows/columns?
- What are the column names and dtypes?
- Are there obviously missing/placeholder values (e.g. `?`, blank strings, `NaN`)?

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       690 non-null    str
 1   1       690 non-null    str
 2   2       690 non-null    float64
 3   3       690 non-null    str
 4   4       690 non-null    str
 5   5       690 non-null    str
 6   6       690 non-null    str
 7   7       690 non-null    float64
 8   8       690 non-null    str
 9   9       690 non-null    str
 10  10      690 non-null    int64
 11  11      690 non-null    str
 12  12      690 non-null    str
 13  13      690 non-null    str
 14  14      690 non-null    int64
 15  15      690 non-null    str
dtypes: float64(2), int64(2), str(12)
memory usage: 86.4 KB

In [62]:
df.describe(include='all')

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
count,690,690,690.000000,690,690,690,690,690.000000,690,690,690.00000,690,690,690,690.000000,690
unique,3,350,NaN,4,4,15,10,NaN,2,2,NaN,2,3,171,NaN,2
top,b,?,NaN,u,g,c,v,NaN,t,f,NaN,f,g,00000,NaN,-
freq,468,12,NaN,519,519,137,399,NaN,361,395,NaN,374,625,132,NaN,383
mean,NaN,NaN,4.758725,NaN,NaN,NaN,NaN,2.223406,NaN,NaN,2.40000,NaN,NaN,NaN,1017.385507,NaN
std,NaN,NaN,4.978163,NaN,NaN,NaN,NaN,3.346513,NaN,NaN,4.86294,NaN,NaN,NaN,5210.102598,NaN
min,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,0.00000,NaN,NaN,NaN,0.000000,NaN
25%,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,0.165000,NaN,NaN,0.00000,NaN,NaN,NaN,0.000000,NaN
50%,NaN,NaN,2.750000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,0.00000,NaN,NaN,NaN,5.000000,NaN
75%,NaN,NaN,7.207500,NaN,NaN,NaN,NaN,2.625000,NaN,NaN,3.00000,NaN,NaN,NaN,395.500000,NaN
max,NaN,NaN,28.000000,NaN,NaN,NaN,NaN,28.500000,NaN,NaN,67.00000,NaN,NaN,NaN,100000.000000,NaN

In [63]:
# This dataset (and several credit datasets like it) use '?' as a missing value placeholder
# instead of a true NaN. Check for that before assuming .isnull() catches everything.
(df == '?').sum()

0     12
1     12
2      0
3      6
4      6
5      9
6      9
7      0
8      0
9      0
10     0
11     0
12     0
13    13
14     0
15     0
dtype: int64

## 3. Standardize missing values

In [64]:
# Replace '?' placeholders with actual NaN so pandas' missing-value tools work correctly
df = df.replace('?', np.nan)

df.isnull().sum()

0     12
1     12
2      0
3      6
4      6
5      9
6      9
7      0
8      0
9      0
10     0
11     0
12     0
13    13
14     0
15     0
dtype: int64

## 4. Rename columns to be human-readable

Some versions of this dataset ship with generic column names (A1, A2, A3...). If yours does, map them
to descriptive names here — this makes every notebook after this one much easier to read and explain
in your README.

**Adjust this dictionary once you see your actual column names from step 2.**

In [65]:
df.head()

  0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  00202    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g  00043  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  00280  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  00100    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  00120    0  +

In [66]:
df.columns = ['gender', 'age', 'debt', 'married', 'bank_customer',
            'education_level', 'ethnicity', 
            'years_employed', 'prior_default', 'employed',
            'credit_score', 'drivers_license', 'citizen', 'zip_code', 'income',
            'approved']

df.columns.tolist()

['gender',
 'age',
 'debt',
 'married',
 'bank_customer',
 'education_level',
 'ethnicity',
 'years_employed',
 'prior_default',
 'employed',
 'credit_score',
 'drivers_license',
 'citizen',
 'zip_code',
 'income',
 'approved']

In [67]:
# Binary Approved and Denied and change this in data frame
df['approved'] = df['approved'].map({'+':1, '-':0})

## 5. Fix data types

Numeric-looking columns sometimes get read in as `object` dtype because of the missing-value placeholders
we just cleaned up. Convert them properly now.

In [68]:
# Identify columns that SHOULD be numeric but got read in as object dtype
# (common after replacing '?' with NaN)
print(df.dtypes)

gender                 str
age                    str
debt               float64
married                str
bank_customer          str
education_level        str
ethnicity              str
years_employed     float64
prior_default          str
employed               str
credit_score         int64
drivers_license        str
citizen                str
zip_code               str
income               int64
approved             int64
dtype: object

In [69]:
# Example: force specific columns to numeric - edit column names to match data
numeric_cols = []  # e.g. ['age', 'debt', 'years_employed', 'credit_score', 'income']

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.dtypes

gender                 str
age                    str
debt               float64
married                str
bank_customer          str
education_level        str
ethnicity              str
years_employed     float64
prior_default          str
employed               str
credit_score         int64
drivers_license        str
citizen                str
zip_code               str
income               int64
approved             int64
dtype: object

## 6. Handle missing values

Decide a strategy per column type — don't default to dropping everything, since that can bias your
dataset if missingness isn't random. Document *why* you chose each strategy; this is worth a line or
two in your README methodology section.

In [70]:
# Numeric columns: fill with median (robust to outliers, common baseline choice)
numeric_missing = df.select_dtypes(include=[np.number]).columns[
    df.select_dtypes(include=[np.number]).isnull().any()
]
for col in numeric_missing:
    df[col] = df[col].fillna(df[col].median())

# Categorical columns: fill with mode (most frequent value)
categorical_missing = df.select_dtypes(include=['object']).columns[
    df.select_dtypes(include=['object']).isnull().any()
]
for col in categorical_missing:
    df[col] = df[col].fillna(df[col].mode()[0])

print("Remaining missing values:")
df.isnull().sum().sum()

Remaining missing values:

/var/folders/cn/7pxxg23s6p1_p4j6jxwqd_rw0000gn/T/ipykernel_37383/675471964.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_missing = df.select_dtypes(include=['object']).columns[
/var/folders/cn/7pxxg23s6p1_p4j6jxwqd_rw0000gn/T/ipykernel_37383/675471964.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include=['object']).isnull().any()

np.int64(0)

## 7. Check the target variable

Look at the class balance now — this determines whether you'll need to handle imbalance later
(e.g. class weighting, SMOTE) in the modeling notebook.

In [71]:
df.columns.tolist()

['gender',
 'age',
 'debt',
 'married',
 'bank_customer',
 'education_level',
 'ethnicity',
 'years_employed',
 'prior_default',
 'employed',
 'credit_score',
 'drivers_license',
 'citizen',
 'zip_code',
 'income',
 'approved']

In [72]:
# Update 'approved' to match your actual target column name
target_col = 'approved'

df[target_col].value_counts()

approved
0    383
1    307
Name: count, dtype: int64

In [73]:
df[target_col].value_counts(normalize=True) * 100

approved
0    55.507246
1    44.492754
Name: proportion, dtype: float64

## 8. Check for duplicates and obvious outliers

In [74]:
print(f"Duplicate rows: {df.duplicated().sum()}")

df = df.drop_duplicates()
df.shape

Duplicate rows: 0

(690, 16)

## 9. Save the cleaned dataset

This is what `02_eda.ipynb` and `03_modeling.ipynb` will load — keeping this separate from raw data
means anyone (including future you) can always trace back to the original source.

In [75]:
df.to_csv('../data/processed/cc_approvals_clean.csv', index=False)
print(f"Saved cleaned dataset: {df.shape[0]} rows, {df.shape[1]} columns")

Saved cleaned dataset: 690 rows, 16 columns

## Summary

*Fill this in once the notebook runs cleanly - a short recap here helps anyone skimming
your repo understand what happened without rereading every cell:*

- Original shape: (690, 16)
- Final shape: (690, 16)
- Missing values handled: Elected to handle numerical values that were missing with median, while categorical data was handled with mode. 
- Columns dropped (if any) and why: No columns dropped, all 16 features retained as potentially predictive.  
- Target variable balance: Was looking for range of 60/40; this was met at 55.507/44.493